spring:
  application:
    name: items-service

server:
  port: ${PORT:0}

eureka:
  instance: 
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka

# Aqui manejamos nuestro timeout entre hystrix y ribbon, en esta caso usamos ribbon ya incluido en eureka.
#ribbon:
#  ConnectTimeout: 3000
#  ReadTimeout: 10000
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 13000
